### ISSUE TITLE
Language vote

### ISSUE THREAD

**Issue by Squidfishrl** [elsys/soft-dev-public#15]
[![](https://api.gh-polls.com/poll/01FGTWRZXYPS7GY8VPTYWHYY7C/Python)](https://api.gh-polls.com/poll/01FGTWRZXYPS7GY8VPTYWHYY7C/Python/vote)
[![](https://api.gh-polls.com/poll/01FGTWRZXYPS7GY8VPTYWHYY7C/Ruby)](https://api.gh-polls.com/poll/01FGTWRZXYPS7GY8VPTYWHYY7C/Ruby/vote)
[![](https://api.gh-polls.com/poll/01FGTWRZXYPS7GY8VPTYWHYY7C/Node.js)](https://api.gh-polls.com/poll/01FGTWRZXYPS7GY8VPTYWHYY7C/Node.js/vote)

**Comment by valeksiev** [comment]
I've voted for Python by accident and then for the rest to even it out. Also, the poll doesn't work for GH's dark theme :D :D  :D
![image](https://user-images.githubusercontent.com/1168275/135416741-79e5199b-a73a-4363-9326-8550672b3997.png)

**Comment by Squidfishrl** [comment]
> I've voted for Python by accident and then for the rest to even it out. Also, the poll doesn't work for GH's dark theme :D :D :D ![image](https://user-images.githubusercontent.com/1168275/135416741-79e5199b-a73a-4363-9326-8550672b3997.png)

I looked into the [polls](https://github.com/apex/gh-polls) API and there isn't dark mode support - the project was developed before github launched dark mode. I won't change the polling method because a lot of votes have already come in. 

As of rn its:
- Python - 21 votes
- Ruby - 13
- Node.js - 7

**Comment by valeksiev** [comment]
Python, it is then! 🐍 🐍 🐍
